import type { Job } from "./jobTypes";

export const allJobs: Job[] = [
  {
    order: 1,
    slug: "qupracs-intern-research-content-prototyping",
    title: "QuPracs Intern (Research / Content / Prototyping)",
    track: "Internships & Early Career",
    team: "Product & Content",
    locations: ["Remote (US-friendly hours)", "San Francisco Bay Area"],
    employmentType: "Internship",
    locationType: "Remote",
    focusTags: ["Content", "Prototyping"],
    compensation: "$30–$60/hr (scope-dependent)",
    summary: "Support Learning content, small prototypes, and practical research notes—shipping clear artifacts every week.",
    overview: [
      "You’ll contribute to Learning, Tutorials, and lightweight prototype work.",
      "You’ll learn by shipping: summaries, diagrams, code snippets, and small evaluations.",
    ],
    responsibilities: [
      "Turn reading into artifacts: summaries, misconception lists, and diagrams.",
      "Support small prototypes with data prep, evaluation, and documentation.",
      "Improve clarity of Learning pages via edits and examples.",
    ],
    requirements: [
      "Clear writing and structured thinking.",
      "Comfort receiving feedback and iterating quickly.",
      "Basic technical comfort (scripting, notebooks, or structured analysis).",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Internship application",
      instructions: [
        "Email us a short note and one sample (writing/code/project summary).",
        "Tell us which track you want: research, content, or prototyping.",
      ],
      askFor: ["Resume or LinkedIn link", "Track preference", "One sample", "Timezone / location"],
    },
  },
  {
    order: 2,
    slug: "qupracs-analyst-intern-enterprise-readiness",
    title: "QuPracs Analyst Intern (Enterprise Readiness)",
    track: "Internships & Early Career",
    team: "Practice",
    locations: ["Remote (US-friendly hours)"],
    employmentType: "Internship",
    locationType: "Remote",
    focusTags: ["Quantum Readiness", "Evaluation"],
    compensation: "$30–$55/hr",
    summary: "Help screen use-cases, build baseline templates, and convert client questions into measurable readiness work.",
    overview: [
      "You’ll support use-case screening and readiness analysis.",
      "You’ll build checklists and baseline-first evaluation artifacts.",
    ],
    responsibilities: [
      "Draft use-case screening briefs and constraints summaries.",
      "Create baseline templates and simple scoring rubrics.",
      "Support delivery with research notes and client-ready summaries.",
    ],
    requirements: [
      "Strong writing and analytical thinking.",
      "Comfort working from ambiguity to a clear structure.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Internship application",
      instructions: ["Email a short note and one sample analysis or writing artifact."],
      askFor: ["Resume or LinkedIn link", "One sample", "Timezone / location"],
    },
  },
  {
    order: 3,
    slug: "engagement-architect-quantum-readiness",
    title: "Engagement Architect (Quantum Readiness)",
    track: "Practice & Delivery",
    team: "Practice",
    locations: ["San Francisco Bay Area", "Remote (US-friendly hours)"],
    employmentType: "Full time",
    locationType: "Hybrid",
    focusTags: ["Quantum Readiness"],
    compensation: "$140K–$200K (DOE) + variable",
    summary: "Scope readiness engagements that are baseline-first and decision-useful—turning hype into measurable plans.",
    overview: [
      "You’ll translate executive goals into constraints, metrics, and milestones.",
      "You’ll keep teams honest: what we can learn in weeks vs what we can’t.",
    ],
    responsibilities: [
      "Run discovery and produce crisp scopes and success metrics.",
      "Build 4–6 week plans with clear milestones and risks.",
      "Coordinate with engineering to keep delivery credible and measurable.",
    ],
    requirements: [
      "Strong client-facing communication and structured thinking.",
      "Comfort resetting expectations early and calmly.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Include one example of a scope you tightened to protect outcomes."],
      askFor: ["Resume or LinkedIn link", "One client story", "Timezone / location"],
    },
  },
  {
    order: 4,
    slug: "customer-relations-manager-qupracs-programs",
    title: "Customer Relations Manager (QuPracs Programs)",
    track: "Practice & Delivery",
    team: "Practice",
    locations: ["San Francisco Bay Area"],
    employmentType: "Full time",
    locationType: "On-site",
    focusTags: ["Quantum Readiness"],
    compensation: "$120K–$175K (DOE) + variable",
    summary: "Own executive-safe communication and customer trust—turning technical reality into decision-ready narratives.",
    overview: [
      "You’ll manage relationship context and keep comms crisp.",
      "You’ll guide customers away from hype while preserving momentum.",
    ],
    responsibilities: [
      "Capture goals, constraints, and decision criteria during discovery.",
      "Write clear follow-ups that align expectations with delivery reality.",
      "Coordinate across PM/engineering to keep clients informed and safe.",
    ],
    requirements: [
      "Exceptional writing and stakeholder communication.",
      "Strong judgment under ambiguity.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Include one example of reframing a hyped request into a measurable plan."],
      askFor: ["Resume or LinkedIn link", "One reframing example", "Timezone / location"],
    },
  },
  {
    order: 5,
    slug: "project-manager-qupracs-delivery",
    title: "Project Manager (QuPracs Delivery)",
    track: "Practice & Delivery",
    team: "Practice Operations",
    locations: ["San Francisco Bay Area", "Remote (US-friendly hours)"],
    employmentType: "Full time",
    locationType: "Hybrid",
    focusTags: ["Quantum Readiness"],
    compensation: "$130K–$190K (DOE)",
    summary: "Run delivery with high signal: scopes, milestones, risks, and honest weekly progress that reduces uncertainty.",
    overview: [
      "You’ll turn vague requests into credible 4–6 week plans.",
      "You’ll own the risk log and expectation alignment.",
    ],
    responsibilities: [
      "Translate requests into objectives, constraints, deliverables, and metrics.",
      "Own cadence: status, blockers, decisions, and stakeholder updates.",
      "Prevent scope creep via explicit tradeoffs.",
    ],
    requirements: [
      "Strong planning discipline and clear written communication.",
      "Comfort operating in technical contexts (constraints and dependencies).",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Send a 1-page sample plan (scope, milestones, risks, metrics)."],
      askFor: ["Resume or LinkedIn link", "One-page plan sample", "Timezone / location"],
    },
  },
  {
    order: 6,
    slug: "solution-consultant-quantum-use-case-screening",
    title: "Solution Consultant (Quantum Use-Case Screening)",
    track: "Practice & Delivery",
    team: "Practice",
    locations: ["San Francisco Bay Area", "Remote (US-friendly hours)"],
    employmentType: "Full time",
    locationType: "Hybrid",
    focusTags: ["Quantum Readiness", "Evaluation"],
    compensation: "$150K–$210K (DOE) + variable",
    summary: "Help teams pick the right problems: screen use-cases, define baselines, and design measurement-first experiments.",
    overview: [
      "You’ll evaluate candidate use-cases against constraints and decision value.",
      "You’ll translate ideas into baseline + metric + experiment plans.",
    ],
    responsibilities: [
      "Run screening workshops and produce decision briefs.",
      "Define baselines and evaluation plans that avoid overclaims.",
      "Partner with engineering to validate feasibility.",
    ],
    requirements: [
      "Strong analytical reasoning and structured communication.",
      "Comfort discussing tradeoffs and constraints with execs.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Include a sample use-case screening outline you’d run."],
      askFor: ["Resume or LinkedIn link", "Screening outline sample", "Timezone / location"],
    },
  },
  {
    order: 7,
    slug: "technical-program-manager-qupracs-partnerships",
    title: "Technical Program Manager (QuPracs Partnerships)",
    track: "Practice & Delivery",
    team: "Practice Operations",
    locations: ["San Francisco Bay Area"],
    employmentType: "Full time",
    locationType: "Hybrid",
    focusTags: ["Platform", "Quantum Readiness"],
    compensation: "$150K–$210K (DOE)",
    summary: "Run partnerships like programs: align stakeholders, define deliverables, and keep integrations honest and measurable.",
    overview: [
      "You’ll coordinate partner motions and technical deliverables.",
      "You’ll keep timelines credible and scope tight.",
    ],
    responsibilities: [
      "Define partner milestones, dependencies, and success metrics.",
      "Coordinate engineering + partner teams for integrations and pilots.",
      "Maintain clear status reporting and risk mitigation.",
    ],
    requirements: [
      "Strong program management and cross-functional leadership.",
      "Comfort reasoning about technical constraints.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Include one example of coordinating a technical partner deliverable."],
      askFor: ["Resume or LinkedIn link", "One partner program story", "Timezone / location"],
    },
  },
  {
    order: 8,
    slug: "full-stack-engineer-qupracs-platform",
    title: "Full Stack Engineer (QuPracs Platform)",
    track: "Engineering",
    team: "Engineering",
    locations: ["Remote (US-friendly hours)", "San Francisco Bay Area"],
    employmentType: "Full time",
    locationType: "Remote",
    focusTags: ["Platform"],
    compensation: "$160K–$230K (DOE)",
    summary: "Build QuPracs internal platform: templates, content pipelines, and lightweight client-facing tooling that stays simple and reliable.",
    overview: [
      "You’ll build internal product surfaces that speed delivery and reduce errors.",
      "You’ll prioritize reproducibility, clarity, and low operational burden.",
    ],
    responsibilities: [
      "Build and maintain web tooling and internal services.",
      "Create reusable templates for prototypes and evaluations.",
      "Improve developer experience (CI, docs, reproducibility).",
    ],
    requirements: [
      "Strong TypeScript/React and Node fundamentals.",
      "Experience shipping maintainable systems.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Share 1–2 links to systems you’ve shipped and maintained."],
      askFor: ["Resume or LinkedIn link", "Two project links", "Timezone / location"],
    },
  },
  {
    order: 9,
    slug: "implementation-engineer-quantum-prototyping-qupracs",
    title: "Implementation Engineer (Quantum Prototyping — QuPracs)",
    track: "Engineering",
    team: "Engineering",
    locations: ["San Francisco Bay Area", "Remote (US-friendly hours)"],
    employmentType: "Full time",
    locationType: "Hybrid",
    focusTags: ["Prototyping", "Quantum Readiness"],
    compensation: "$150K–$210K (DOE) + equity (where applicable)",
    summary: "Build baseline-first prototypes and implementation artifacts—shipping disciplined experiments that teach something real.",
    overview: [
      "You’ll convert ambiguous requests into measurable prototypes.",
      "You’ll document limits clearly and propose next experiments.",
    ],
    responsibilities: [
      "Define baselines and metrics before novelty.",
      "Build prototypes and demos with clean interfaces and validation.",
      "Write short notes explaining assumptions and constraints.",
    ],
    requirements: [
      "Strong engineering fundamentals and debugging discipline.",
      "Proficiency in TypeScript/Node or Python.",
      "Comfort working in ambiguity and iterating quickly.",
    ],
    niceToHave: ["Optimization/ML background", "Quantum tooling familiarity"],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Include one work sample that shows measurement and restraint."],
      askFor: ["Resume or LinkedIn link", "One work sample", "Timezone / location"],
    },
  },
  {
    order: 10,
    slug: "research-engineer-optimization-quantum-workflows",
    title: "Research Engineer (Optimization / Quantum Workflows)",
    track: "Engineering",
    team: "Engineering",
    locations: ["San Francisco Bay Area", "Remote (US-friendly hours)"],
    employmentType: "Full time",
    locationType: "Hybrid",
    focusTags: ["Evaluation", "Quantum Readiness"],
    compensation: "$170K–$240K (DOE)",
    summary: "Design baselines, evaluate heuristics, and turn promising quantum workflows into evidence with careful measurement.",
    overview: [
      "You’ll build benchmarkable problem formulations and baselines.",
      "You’ll run disciplined evaluations and communicate results clearly.",
    ],
    responsibilities: [
      "Implement baselines and evaluation harnesses.",
      "Run experiments with sanity checks and clear metrics.",
      "Write decision-ready recommendations with limits.",
    ],
    requirements: [
      "Strong Python and scientific computing fundamentals.",
      "Experience with optimization or algorithm evaluation.",
    ],
    niceToHave: ["OR tools (OR-Tools, Gurobi, etc.)", "Quantum optimization exposure"],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Include one example where you measured an algorithm honestly."],
      askFor: ["Resume or LinkedIn link", "One evaluation artifact", "Timezone / location"],
    },
  },
  {
    order: 11,
    slug: "benchmarking-engineer-baselines-evaluation-qupracs",
    title: "Benchmarking Engineer (Baselines & Evaluation — QuPracs)",
    track: "Engineering",
    team: "Engineering",
    locations: ["Remote (US-friendly hours)", "San Francisco Bay Area"],
    employmentType: "Full time",
    locationType: "Remote",
    focusTags: ["Evaluation"],
    compensation: "$160K–$230K (DOE)",
    summary: "Own benchmarking: reproducible baselines, fair comparisons, and clean reporting that prevents overclaims.",
    overview: [
      "You’ll design benchmark suites and evaluation harnesses.",
      "You’ll keep results reproducible and easy to interpret.",
    ],
    responsibilities: [
      "Create reusable benchmark datasets and harnesses.",
      "Define metrics and comparison methodology.",
      "Publish clear reports that state limits.",
    ],
    requirements: [
      "Experience building reliable evaluation pipelines.",
      "Strong programming fundamentals (Python preferred).",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Include a benchmark/evaluation system you’ve built."],
      askFor: ["Resume or LinkedIn link", "Benchmarking example", "Timezone / location"],
    },
  },
  {
    order: 12,
    slug: "data-ml-engineer-hybrid-quantum-pipelines",
    title: "Data/ML Engineer (Hybrid Quantum Pipelines)",
    track: "Engineering",
    team: "Engineering",
    locations: ["Remote (US-friendly hours)"],
    employmentType: "Full time",
    locationType: "Remote",
    focusTags: ["Platform", "Prototyping"],
    compensation: "$160K–$230K (DOE)",
    summary: "Build data and ML pipelines that support hybrid workflows—clean baselines, reproducible runs, and practical integrations.",
    overview: [
      "You’ll build pipelines that make experiments reproducible and reviewable.",
      "You’ll keep operational burden low and clarity high.",
    ],
    responsibilities: [
      "Build dataset and feature pipelines for evaluations.",
      "Implement reproducible experiment tracking and reporting.",
      "Partner with engineers/researchers on integration needs.",
    ],
    requirements: [
      "Strong data engineering or ML engineering fundamentals.",
      "Comfort building reliable pipelines and instrumentation.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Include a pipeline you owned end-to-end and how you validated it."],
      askFor: ["Resume or LinkedIn link", "One pipeline example", "Timezone / location"],
    },
  },
  {
    order: 13,
    slug: "developer-advocate-qupracs-tooling-tutorials",
    title: "Developer Advocate (QuPracs Tooling & Tutorials)",
    track: "Product, Learning & Thought Leadership",
    team: "Product & Content",
    locations: ["Remote (US-friendly hours)", "San Francisco Bay Area"],
    employmentType: "Full time",
    locationType: "Remote",
    focusTags: ["Content", "Platform"],
    compensation: "$130K–$190K (DOE)",
    summary: "Teach by building: honest demos, tutorials, and sample repos that make tradeoffs and constraints explicit.",
    overview: [
      "You’ll write tutorials and ship reference implementations.",
      "You’ll connect Learning, Tutorials, and real deployment constraints.",
    ],
    responsibilities: [
      "Build small sample projects and tutorial code.",
      "Write walkthroughs that emphasize baselines and constraints.",
      "Gather feedback and improve content/tooling loops.",
    ],
    requirements: [
      "Strong engineering skills and the ability to teach.",
      "Clear writing and communication.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Include one tutorial or repo you’re proud of."],
      askFor: ["Resume or LinkedIn link", "One content link", "Timezone / location"],
    },
  },
  {
    order: 14,
    slug: "technical-writer-quantum-decision-making",
    title: "Technical Writer (Quantum & Decision-Making)",
    track: "Product, Learning & Thought Leadership",
    team: "Product & Content",
    locations: ["Remote (US-friendly hours)"],
    employmentType: "Full time",
    locationType: "Remote",
    focusTags: ["Content", "Quantum Readiness"],
    compensation: "$110K–$170K (DOE)",
    summary: "Write constraint-honest learning content: what’s real, what’s not, and how to decide—without oversimplifying truth.",
    overview: [
      "You’ll produce Learning pages, blogs, and tutorials with a consistent voice.",
      "You’ll make complex topics usable and precise.",
    ],
    responsibilities: [
      "Turn messy notes into crisp Learning content.",
      "Develop diagrams, checklists, and decision frameworks.",
      "Maintain editorial standards and reduce ambiguity.",
    ],
    requirements: [
      "Strong technical writing portfolio.",
      "Ability to explain assumptions, tradeoffs, and limits.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Send 2–3 writing samples and a short note about your process."],
      askFor: ["Resume or LinkedIn link", "2–3 writing samples", "Timezone / location"],
    },
  },
  {
    order: 15,
    slug: "curriculum-lead-qupracs-learning-track-quantum-readiness",
    title: "Curriculum Lead (QuPracs Learning Track — Quantum Readiness)",
    track: "Product, Learning & Thought Leadership",
    team: "Product & Content",
    locations: ["Remote (US-friendly hours)"],
    employmentType: "Full time",
    locationType: "Remote",
    focusTags: ["Content", "Quantum Readiness"],
    compensation: "$130K–$190K (DOE)",
    summary: "Own the Learning track end-to-end: structure, pedagogy, and high-signal content that reduces confusion and hype.",
    overview: [
      "You’ll define learning objectives and content standards.",
      "You’ll coordinate SMEs and ship coherent curriculum.",
    ],
    responsibilities: [
      "Define scope and sequencing of the readiness curriculum.",
      "Review and edit content for clarity, precision, and usefulness.",
      "Measure content effectiveness and iterate.",
    ],
    requirements: [
      "Strong curriculum design and writing/editing skills.",
      "Ability to balance accessibility with technical truth.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Include one curriculum artifact you’ve owned (outline, syllabus, or learning path)."],
      askFor: ["Resume or LinkedIn link", "One curriculum artifact", "Timezone / location"],
    },
  },
  {
    order: 16,
    slug: "account-executive-enterprise-qupracs-quantum-advisory",
    title: "Account Executive (Enterprise — QuPracs Quantum Advisory)",
    track: "Sales & Revenue",
    team: "Sales",
    locations: ["San Francisco Bay Area", "Remote (US-friendly hours)"],
    employmentType: "Full time",
    locationType: "Hybrid",
    focusTags: ["Quantum Readiness"],
    compensation: "$120K–$170K base + commission",
    summary: "Sell carefully: help execs buy clarity and readiness, not demos—measured on trust, retention, and decision outcomes.",
    overview: [
      "You’ll qualify enterprise accounts and run discovery with Practice.",
      "You’ll scope readiness engagements with clear deliverables.",
    ],
    responsibilities: [
      "Prospect and qualify enterprise accounts.",
      "Coordinate discovery and scope proposals.",
      "Maintain high-signal pipeline hygiene.",
    ],
    requirements: [
      "Enterprise sales experience in technical services or SaaS.",
      "Comfort selling nuance and constraints.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Include one example of slowing a deal down to protect trust—and why."],
      askFor: ["Resume or LinkedIn link", "One trust-first sales story", "Timezone / location"],
    },
  },
  {
    order: 17,
    slug: "revenue-operations-lead-enterprise",
    title: "Revenue Operations Lead (Enterprise)",
    track: "Sales & Revenue",
    team: "Sales Ops",
    locations: ["Remote (US-friendly hours)", "San Francisco Bay Area"],
    employmentType: "Full time",
    locationType: "Remote",
    focusTags: ["Platform"],
    compensation: "$120K–$180K (DOE)",
    summary: "Build a clean operating system for growth: pipeline metrics, process, and instrumentation—high signal, low busywork.",
    overview: [
      "You’ll define funnel metrics and create honest reporting.",
      "You’ll reduce friction across handoffs.",
    ],
    responsibilities: [
      "Instrument funnel and forecast inputs.",
      "Own CRM hygiene standards and automation.",
      "Partner with Sales/Practice to improve handoffs.",
    ],
    requirements: [
      "RevOps experience with strong analytics.",
      "Comfort building simple, maintainable systems.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Share one metric system you built and how it changed decisions."],
      askFor: ["Resume or LinkedIn link", "Metrics system example", "Timezone / location"],
    },
  },
  {
    order: 18,
    slug: "sales-engineer-qupracs-quantum-readiness-pocs",
    title: "Sales Engineer (QuPracs Quantum Readiness & POCs)",
    track: "Sales & Revenue",
    team: "Sales",
    locations: ["San Francisco Bay Area", "Remote (US-friendly hours)"],
    employmentType: "Full time",
    locationType: "Hybrid",
    focusTags: ["Quantum Readiness", "Prototyping"],
    compensation: "$150K–$220K (DOE) + variable",
    summary: "Bridge sales and delivery: run technical discovery, scope POCs honestly, and protect credibility with baseline-first framing.",
    overview: [
      "You’ll support discovery and solution framing for enterprise prospects.",
      "You’ll keep proposals measurable and constraint-honest.",
    ],
    responsibilities: [
      "Run technical discovery and produce solution narratives.",
      "Define baselines, metrics, and POC scope.",
      "Coordinate with engineering to validate feasibility.",
    ],
    requirements: [
      "Strong technical communication and stakeholder skills.",
      "Ability to translate constraints into credible plans.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Include one example of a POC you scoped to protect outcomes."],
      askFor: ["Resume or LinkedIn link", "One POC story", "Timezone / location"],
    },
  },
  {
    order: 19,
    slug: "operations-manager",
    title: "Operations Manager",
    track: "Operations",
    team: "Operations",
    locations: ["San Francisco Bay Area"],
    employmentType: "Full time",
    locationType: "On-site",
    focusTags: ["Platform"],
    compensation: "$110K–$160K (DOE)",
    summary: "Own the operational backbone: scheduling, vendor management, basic finance ops, and process hygiene so delivery stays focused.",
    overview: [
      "You’ll reduce friction and keep execution smooth.",
      "You’ll build simple processes that scale.",
    ],
    responsibilities: [
      "Manage scheduling and operational logistics.",
      "Maintain vendors, purchasing workflows, and internal process docs.",
      "Support light finance ops (invoicing coordination, budget tracking).",
    ],
    requirements: [
      "Strong organization and written communication.",
      "Ability to prioritize and reduce chaos.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Include an example of a process you simplified and how you measured improvement."],
      askFor: ["Resume or LinkedIn link", "Process improvement example", "Timezone / location"],
    },
  },
  {
    order: 20,
    slug: "recruiting-talent-partner-qupracs-practice-engineering",
    title: "Recruiting / Talent Partner (QuPracs Practice & Engineering)",
    track: "Operations",
    team: "Operations",
    locations: ["Remote (US-friendly hours)"],
    employmentType: "Contract",
    locationType: "Remote",
    focusTags: ["Platform"],
    compensation: "$60–$120/hr (scope-dependent)",
    summary: "Own talent pipeline for Practice and Engineering: sourcing, screening, and process quality—high signal, low noise.",
    overview: [
      "You’ll build a repeatable recruiting motion that matches our judgment-first bar.",
      "You’ll maintain a fair, transparent process and strong candidate experience.",
    ],
    responsibilities: [
      "Source and screen candidates for key roles.",
      "Run a structured pipeline with clean notes and rubrics.",
      "Partner with hiring leads to keep interviews calibrated.",
    ],
    requirements: [
      "Recruiting experience across technical and client-facing roles.",
      "Strong communication and process discipline.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Talent partnership",
      instructions: ["Email a short note and examples of roles you’ve filled end-to-end."],
      askFor: ["LinkedIn link", "Roles filled (examples)", "Availability", "Timezone / location"],
    },
  },
];
