import type { Job } from "./jobTypes";

export const allJobs: Job[] = [
  // Core roles
  {
    order: 1,
    slug: "implementation-project-manager-client-delivery",
    title: "Delivery Manager",
    track: "Practice & Delivery",
    team: "Practice Operations",
    locations: ["San Francisco Bay Area", "Remote (US-friendly hours)"],
    employmentType: "Full time",
    locationType: "Hybrid",
    focusTags: ["Evaluation"],
    summary: "Own onboarding, timelines, a lightweight RAID log, and weekly delivery hygiene—keeping work decision-grade and credible.",
    credibilityBullets: {
      outcome90Days: "Run 2–4 client workstreams end-to-end with crisp scopes, pragmatic status, and measurable outcomes.",
      skills: "Delivery PM fundamentals: scopes, milestones, risks, stakeholder comms, and tight written updates.",
      niceToHave: "Comfort in technical contexts (constraints, baselines, integrations) without pretending to be the engineer.",
    },
    overview: [
      "We work in messy, hyped domains. Your job is to keep delivery calm, measurable, and pragmatic.",
      "You’ll translate requests into a plan teams can execute—and keep the promise surface small and credible.",
    ],
    responsibilities: [
      "Own onboarding: context capture, success criteria, milestones, and the first plan.",
      "Run cadence: weekly status, decision log, risks, and mitigations.",
      "Prevent scope creep via explicit tradeoffs and written alignment.",
    ],
    requirements: [
      "Strong planning discipline and executive-safe writing.",
      "Comfort operating in ambiguity and converging to a clear plan.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Send a short note and a 1-page sample plan (scope, milestones, risks, metrics)."],
      askFor: ["Resume or LinkedIn link", "One-page plan sample", "Timezone / location"],
    },
  },
  {
    order: 2,
    slug: "sales-manager-enterprise",
    title: "Sales Manager (Enterprise)",
    track: "Sales & Revenue",
    team: "Sales",
    locations: ["San Francisco Bay Area", "Remote (US-friendly hours)"],
    employmentType: "Full time",
    locationType: "Hybrid",
    summary: "Own pipeline and discovery calls. Qualify fit, protect credibility, and turn interest into scoped work with clear outcomes.",
    credibilityBullets: {
      outcome90Days: "Run discovery and qualify conversations into a small set of clearly scoped engagements.",
      skills: "Enterprise discovery + qualification with crisp notes and disciplined next steps (no vague pilot theater).",
      niceToHave: "Bay Area enterprise network or prior experience selling technical services / consulting.",
    },
    overview: [
      "We sell disciplined work: baseline-first evaluation, measurable prototypes, and executive-safe decision memos.",
      "You’ll help prospects move from curiosity to a concrete scope—or politely disqualify when it’s not a fit.",
    ],
    responsibilities: [
      "Run discovery calls; capture goals, constraints, baselines, and decision criteria.",
      "Coordinate with delivery to shape scopes, timelines, and success metrics.",
      "Maintain simple funnel metrics and follow-up hygiene.",
    ],
    requirements: [
      "Strong sales fundamentals and structured communication.",
      "Comfort selling reality and constraints (not hype).",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Include one example of a deal you disqualified and why."],
      askFor: ["Resume or LinkedIn link", "One disqualification story", "Timezone / location"],
    },
  },
  {
    order: 3,
    slug: "engagement-architect-presales-solutions",
    title: "Engagement Architect (Pre-sales / Solutions)",
    track: "Sales & Revenue",
    team: "Sales",
    locations: ["San Francisco Bay Area", "Remote (US-friendly hours)"],
    employmentType: "Full time",
    locationType: "Hybrid",
    focusTags: ["Evaluation"],
    summary: "Bridge sales → delivery: shape pilots, scope sprints, and write POV docs that stay baseline-first and measurable.",
    credibilityBullets: {
      outcome90Days: "Turn top opportunities into crisp 4–6 week scopes with risks, baselines, and success metrics.",
      skills: "Solution shaping, technical writing, and translating goals into constraints and milestones.",
      niceToHave: "Experience with architecture/integration discussions (data, security, latency, governance).",
    },
    overview: [
      "Your deliverable is clarity: what we’ll learn, what we won’t, and what ‘success’ means.",
      "You’ll prevent innovation theater by insisting on baselines, measurement, and explicit assumptions.",
    ],
    responsibilities: [
      "Write short POV/scope docs that define constraints, baselines, and outcomes.",
      "Partner with engineering to validate feasibility and reduce promise surface.",
      "Support handoff into delivery with clean decision criteria.",
    ],
    requirements: [
      "Strong client-facing communication and structured thinking.",
      "Comfort saying ‘no’ early to protect credibility.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Include one scope/POV example (or outline) you tightened to protect outcomes."],
      askFor: ["Resume or LinkedIn link", "One scope/POV sample", "Timezone / location"],
    },
  },
  {
    order: 4,
    slug: "full-stack-engineer-platform",
    title: "Full Stack Engineer (Platform)",
    track: "Engineering",
    team: "Engineering",
    locations: ["Remote (US-friendly hours)", "San Francisco Bay Area"],
    employmentType: "Full time",
    locationType: "Remote",
    focusTags: ["Platform"],
    summary: "Build simple, reliable product workflows: site + tooling + learning/tutorial plumbing—optimized for shipping and low ops burden.",
    credibilityBullets: {
      outcome90Days: "Ship 2–4 end-to-end improvements across content + tutorials + internal workflows with clean reliability.",
      skills: "TypeScript/React/Next.js, pragmatic API work, and comfort owning features end-to-end.",
      niceToHave: "Experience with developer tooling, CI, content pipelines, or lightweight infra.",
    },
    overview: [
      "We value speed with correctness: simple systems that stay maintainable.",
      "You’ll help keep content, demos, and small tools cohesive and reliable.",
    ],
    responsibilities: [
      "Build and maintain web features and small internal tools.",
      "Improve reliability and clarity across the tutorial runner UX.",
      "Keep implementation simple: minimal moving parts, strong defaults.",
    ],
    requirements: [
      "Strong TypeScript/React fundamentals.",
      "Comfort shipping and maintaining production code.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Share 1–2 links to systems you’ve shipped and maintained."],
      askFor: ["Resume or LinkedIn link", "Links to shipped work", "Timezone / location"],
    },
  },
  {
    order: 5,
    slug: "research-engineer-optimization-qc-applications",
    title: "Research Engineer (Optimization / QC Applications)",
    track: "Engineering",
    team: "Engineering",
    locations: ["Remote (US-friendly hours)", "San Francisco Bay Area"],
    employmentType: "Full time",
    locationType: "Remote",
    focusTags: ["Evaluation"],
    summary: "Build and benchmark problem formulations + baselines across solvers/QPUs/sim—keeping claims disciplined and decision-grade.",
    credibilityBullets: {
      outcome90Days: "Deliver 2–3 benchmarked evaluations with baselines, assumptions, and reproducible artifacts.",
      skills: "Optimization/applied math foundations, experimental discipline, and clean reproducible code.",
      niceToHave: "Familiarity with OR/MIP/QUBO/Ising or hybrid workflows; comfort writing clear decision memos.",
    },
    overview: [
      "We care about baseline-first evaluation and pragmatic constraints.",
      "You’ll turn vague use-cases into clear formulations and measurement plans.",
    ],
    responsibilities: [
      "Define formulations and compare against classical baselines.",
      "Build evaluation pipelines and produce decision-grade summaries.",
      "Partner with delivery to keep prototypes measurable and credible.",
    ],
    requirements: [
      "Strong analytical reasoning and comfort with experimentation.",
      "Ability to write clear, reproducible code.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Share one example of a baseline you built and how you validated it."],
      askFor: ["Resume or LinkedIn link", "One baseline example", "Timezone / location"],
    },
  },

  // Internships
  {
    order: 10,
    slug: "intern-quantum-research-optimization-or",
    title: "Quantum Research Intern (Optimization / OR)",
    track: "Internships & Early Career",
    team: "Practice",
    locations: ["Remote (US-friendly hours)", "San Francisco Bay Area"],
    employmentType: "Internship",
    locationType: "Remote",
    focusTags: ["Evaluation"],
    compensation: "$30–$60/hr (scope-dependent)",
    summary: "Support benchmarking work: formulations, baselines, and short memos—shipping small, credible artifacts weekly.",
    credibilityBullets: {
      outcome90Days: "Ship a steady stream of small research artifacts (benchmarks, notes, diagrams, short memos).",
      skills: "Comfort with OR/optimization basics and structured writing.",
      niceToHave: "Python notebooks and curiosity for experimental discipline.",
    },
    overview: [
      "You’ll learn by shipping: small benchmarks, baselines, and short readable summaries.",
      "This is practical work: reproducibility and clarity matter more than novelty.",
    ],
    responsibilities: [
      "Implement or reproduce baseline comparisons from papers/blogs.",
      "Write short memos: what worked, what didn’t, and what assumptions mattered.",
      "Maintain clean, searchable artifacts (notes + links + code snippets).",
    ],
    requirements: [
      "Clear communication and strong follow-through.",
      "Comfort being coached and iterating fast.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Internship application",
      instructions: ["Email us a short note and one sample (writing, analysis, or code)."],
      askFor: ["Resume or LinkedIn link", "One sample", "Timezone / location"],
    },
  },
  {
    order: 11,
    slug: "intern-software-engineering-platform-full-stack",
    title: "Software Engineering Intern (Platform / Full Stack)",
    track: "Internships & Early Career",
    team: "Engineering",
    locations: ["Remote (US-friendly hours)", "San Francisco Bay Area"],
    employmentType: "Internship",
    locationType: "Remote",
    focusTags: ["Platform"],
    compensation: "$30–$60/hr (scope-dependent)",
    summary: "Ship small end-to-end improvements across the site and tutorial experience with good hygiene and fast iteration.",
    credibilityBullets: {
      outcome90Days: "Ship 4–8 small PRs that improve reliability, UX, or content plumbing.",
      skills: "Basic web dev fundamentals (React/TypeScript) and a bias to shipping.",
      niceToHave: "Comfort with testing, CI, or working in a modern Next.js codebase.",
    },
    overview: [
      "You’ll work in a real codebase with real constraints.",
      "We prefer small, shippable improvements over sprawling rewrites.",
    ],
    responsibilities: [
      "Implement small features and fixes across site and tutorials.",
      "Improve developer ergonomics (docs, scripts, reliability).",
      "Write clear PR descriptions and accept feedback.",
    ],
    requirements: [
      "Comfort learning quickly and asking crisp questions.",
      "Care for code clarity and maintainability.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Internship application",
      instructions: ["Email us a short note and a link to one project/repo (or a short sample)."],
      askFor: ["Resume or LinkedIn link", "One project/repo link", "Timezone / location"],
    },
  },
  {
    order: 12,
    slug: "intern-content-research-briefs-blogs",
    title: "Content & Research Intern (Executive Briefs + Blogs)",
    track: "Internships & Early Career",
    team: "Product & Content",
    locations: ["Remote (US-friendly hours)", "San Francisco Bay Area"],
    employmentType: "Internship",
    locationType: "Remote",
    focusTags: ["Content"],
    compensation: "$25–$55/hr (scope-dependent)",
    summary: "Turn reading and delivery notes into crisp artifacts: briefs, diagrams, and blog drafts that stay decision-first.",
    credibilityBullets: {
      outcome90Days: "Ship multiple publishable drafts or internal briefs with clean structure and citations.",
      skills: "Strong writing/editing and ability to distill messy inputs into a clear outline.",
      niceToHave: "Comfort with technical topics and simple visual diagrams.",
    },
    overview: [
      "We write for decision-makers and builders: baseline-first, measurable, hype-resistant.",
      "You’ll ship weekly: short artifacts with clear structure.",
    ],
    responsibilities: [
      "Draft executive briefs and blog outlines from source material.",
      "Edit for clarity, tone, and measurable claims.",
      "Maintain a simple backlog of topics and supporting links.",
    ],
    requirements: [
      "Excellent writing and comfort receiving feedback.",
      "Strong organizational habits.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Internship application",
      instructions: ["Email us a short note and one writing sample (published or private)."],
      askFor: ["Resume or LinkedIn link", "One writing sample", "Timezone / location"],
    },
  },
  {
    order: 13,
    slug: "intern-go-to-market-lead-research-outreach-ops",
    title: "Go-to-Market Intern (Lead Research + Outreach Ops)",
    track: "Internships & Early Career",
    team: "Sales Ops",
    locations: ["Remote (US-friendly hours)", "San Francisco Bay Area"],
    employmentType: "Internship",
    locationType: "Remote",
    compensation: "$25–$50/hr (scope-dependent)",
    summary: "Support lead research, outreach ops, and CRM hygiene—helping the team keep the funnel high-signal.",
    credibilityBullets: {
      outcome90Days: "Build 1–2 tight lead lists and keep outreach + CRM hygiene clean and measurable.",
      skills: "Strong organization, writing, and comfort with systems (spreadsheets/CRM).",
      niceToHave: "Prior GTM ops experience or strong research habits (clean notes, tags, follow-ups).",
    },
    overview: [
      "This is operational excellence: clean data, clean follow-up, and disciplined notes.",
      "You’ll learn how technical services are qualified and scoped.",
    ],
    responsibilities: [
      "Research target accounts and contacts; keep notes consistent.",
      "Support outreach workflows and follow-up hygiene.",
      "Maintain simple metrics and reporting.",
    ],
    requirements: [
      "High attention to detail and strong follow-through.",
      "Clear written communication.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Internship application",
      instructions: ["Email a short note and one sample (a research brief, writing sample, or project summary)."],
      askFor: ["Resume or LinkedIn link", "One sample", "Timezone / location"],
    },
  },
  {
    order: 14,
    slug: "intern-design-ux-site-diagrams-decks",
    title: "Design / UX Intern (Site + Diagrams + Decks)",
    track: "Internships & Early Career",
    team: "Product & Content",
    locations: ["Remote (US-friendly hours)", "San Francisco Bay Area"],
    employmentType: "Internship",
    locationType: "Remote",
    compensation: "$25–$55/hr (scope-dependent)",
    summary: "Help improve the site and artifacts: diagrams, simple UX polish, and clean client-facing visuals.",
    credibilityBullets: {
      outcome90Days: "Ship a set of design artifacts (diagrams, page polish, deck visuals) that improve clarity.",
      skills: "Strong visual communication and ability to iterate quickly from feedback.",
      niceToHave: "Comfort with Figma and turning messy notes into crisp diagrams.",
    },
    overview: [
      "We care about clarity and credibility—visuals should reduce confusion, not add marketing gloss.",
      "You’ll work closely with content and delivery to make outputs easier to understand.",
    ],
    responsibilities: [
      "Create diagrams and visuals for posts, learning modules, and briefs.",
      "Suggest small UX improvements that reduce friction.",
      "Maintain lightweight consistency (colors, typography, reusable components).",
    ],
    requirements: [
      "Strong visual craft and attention to detail.",
      "Comfort iterating quickly and sharing work-in-progress.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Internship application",
      instructions: ["Email a short note and 2–4 portfolio links/screenshots."],
      askFor: ["Resume or LinkedIn link", "Portfolio", "Timezone / location"],
    },
  },

  // Open application
  {
    order: 99,
    slug: "open-application-intern-contractor-advisor",
    title: "Open Application — Intern / Contractor / Advisor",
    track: "Operations",
    team: "Operations",
    locations: ["Remote (US-friendly hours)", "San Francisco Bay Area"],
    employmentType: "Contract",
    locationType: "Remote",
    summary: "If you’re a fit for QuPracs but don’t see the exact role, reach out. Keep it short and high-signal.",
    credibilityBullets: {
      outcome90Days: "Propose one concrete outcome you can deliver in 4–8 weeks.",
      skills: "Clear writing, disciplined execution, and the ability to ship decision-grade artifacts.",
      niceToHave: "Prior experience in technical delivery, enterprise work, or disciplined research workflows.",
    },
    overview: [
      "We’re small and selective. We optimize for credibility: baseline-first, measurable work.",
      "If you can help us move faster without adding fragility, we want to hear from you.",
    ],
    responsibilities: [
      "Tell us what role you’re aiming for and why you’re a fit.",
      "Share one artifact you’ve shipped (memo, analysis, repo, deck).",
    ],
    requirements: [
      "Clear communication.",
      "Bias to shipping measurable outputs.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Open application",
      instructions: ["Email us with a short note and one sample."],
      askFor: ["Resume or LinkedIn link", "What role you’re aiming for", "One sample", "Timezone / location"],
    },
  },
];

/*
The block below is legacy content that previously lived in this file.
It is intentionally commented out to keep the active jobs list small and credible.

export const allJobs: Job[] = [
  {
    order: 1,
    slug: "qupracs-intern-research-content-prototyping",
    title: "QuPracs Intern (Research / Content / Prototyping)",
    track: "Internships & Early Career",
    team: "Product & Content",
    locations: ["Remote (US-friendly hours)", "San Francisco Bay Area"],
    employmentType: "Internship",
    locationType: "Remote",
    focusTags: ["Content", "Prototyping"],
    compensation: "$30–$60/hr (scope-dependent)",
    summary: "Support Learning content, small prototypes, and practical research notes—shipping clear artifacts every week.",
    overview: [
      "You’ll contribute to Learning, Tutorials, and lightweight prototype work.",
      "You’ll learn by shipping: summaries, diagrams, code snippets, and small evaluations.",
    ],
    responsibilities: [
      "Turn reading into artifacts: summaries, misconception lists, and diagrams.",
      "Support small prototypes with data prep, evaluation, and documentation.",
      "Improve clarity of Learning pages via edits and examples.",
    ],
    requirements: [
      "Clear writing and structured thinking.",
      "Comfort receiving feedback and iterating quickly.",
      "Basic technical comfort (scripting, notebooks, or structured analysis).",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Internship application",
      instructions: [
        "Email us a short note and one sample (writing/code/project summary).",
        "Tell us which track you want: research, content, or prototyping.",
      ],
      askFor: ["Resume or LinkedIn link", "Track preference", "One sample", "Timezone / location"],
    },
        {
          order: 1,
          slug: "project-manager-client-delivery",
          title: "Delivery Manager",
          track: "Practice & Delivery",
          team: "Practice Operations",
          locations: ["San Francisco Bay Area", "Remote (US-friendly hours)"],
          employmentType: "Full time",
          locationType: "Hybrid",
          focusTags: ["Evaluation"],
          summary: "Own onboarding, timelines, a lightweight RAID log, and weekly delivery hygiene—keeping work decision-grade and credible.",
          credibilityBullets: {
            outcome90Days: "Run 2–4 client workstreams end-to-end with crisp scopes, pragmatic status, and measurable outcomes.",
            skills: "Client delivery PM fundamentals: scopes, milestones, risks, stakeholder comms, and tight written updates.",
            niceToHave: "Comfort in technical contexts (constraints, baselines, integrations) without pretending to be the engineer.",
          },
          overview: [
            "We work in messy, hyped domains. Your job is to keep delivery calm, measurable, and pragmatic.",
            "You’ll translate requests into a plan teams can execute—and keep the promise surface small and credible.",
          ],
          responsibilities: [
            "Own onboarding: context capture, success criteria, milestones, and the first plan.",
            "Run cadence: weekly status, decision log, risks, and mitigations.",
            "Prevent scope creep via explicit tradeoffs and written alignment.",
          ],
          requirements: [
            "Strong planning discipline and executive-safe writing.",
            "Comfort operating in ambiguity and converging to a clear plan.",
          ],
          application: {
            emailTo: "careers@qupracs.com",
            subjectPrefix: "Application",
            instructions: ["Send a short note and a 1-page sample plan (scope, milestones, risks, metrics)."],
            askFor: ["Resume or LinkedIn link", "One-page plan sample", "Timezone / location"],
          },
        },
        {
          order: 2,
          slug: "sales-manager-enterprise",
          title: "Sales Manager (Enterprise)",
          track: "Sales & Revenue",
          team: "Sales",
          locations: ["San Francisco Bay Area", "Remote (US-friendly hours)"],
          employmentType: "Full time",
          locationType: "Hybrid",
          summary: "Own pipeline and discovery calls. Qualify fit, protect credibility, and turn interest into scoped work with clear outcomes.",
          credibilityBullets: {
            outcome90Days: "Run discovery and qualify 15–30 conversations into a small set of clearly scoped engagements.",
            skills: "Enterprise discovery, qualification, crisp notes, and disciplined next steps (no vague pilot theater).",
            niceToHave: "Bay Area enterprise network or prior experience selling technical services / consulting.",
          },
          overview: [
            "We sell disciplined work: baseline-first evaluation, measurable prototypes, and executive-safe decision memos.",
            "You’ll help prospects move from curiosity to a concrete scope—or politely disqualify when it’s not a fit.",
          ],
          responsibilities: [
            "Run discovery calls; capture goals, constraints, baselines, and decision criteria.",
            "Coordinate with delivery to shape scopes, timelines, and success metrics.",
            "Maintain simple funnel metrics and follow-up hygiene.",
          ],
          requirements: [
            "Strong sales fundamentals and structured communication.",
            "Comfort selling reality and constraints (not hype).",
          ],
          application: {
            emailTo: "careers@qupracs.com",
            subjectPrefix: "Application",
            instructions: ["Include one example of a deal you disqualified and why."],
            askFor: ["Resume or LinkedIn link", "One disqualification story", "Timezone / location"],
          },
        },
        {
          order: 3,
          slug: "engagement-architect-presales-solutions",
          title: "Engagement Architect (Pre-sales / Solutions)",
          track: "Sales & Revenue",
          team: "Sales",
          locations: ["San Francisco Bay Area", "Remote (US-friendly hours)"],
          employmentType: "Full time",
          locationType: "Hybrid",
          focusTags: ["Evaluation"],
          summary: "Bridge sales → delivery: shape pilots, scope sprints, and write POV docs that stay baseline-first and measurable.",
          credibilityBullets: {
            outcome90Days: "Turn top opportunities into crisp 4–6 week scopes with risks, baselines, and success metrics.",
            skills: "Solution shaping, technical writing, stakeholder alignment, and translating goals into constraints and milestones.",
            niceToHave: "Experience with architecture/integration discussions (data, security, latency, governance).",
          },
          overview: [
            "Your deliverable is clarity: what we’ll learn, what we won’t, and what ‘success’ means.",
            "You’ll prevent “innovation theater” by insisting on baselines, measurement, and explicit assumptions.",
          ],
          responsibilities: [
            "Write short POV/scope docs that define constraints, baselines, and outcomes.",
            "Partner with engineering to validate feasibility and reduce promise surface.",
            "Support handoff into delivery with clean decision criteria.",
          ],
          requirements: [
            "Strong client-facing communication and structured thinking.",
            "Comfort saying ‘no’ early to protect credibility.",
          ],
          application: {
            emailTo: "careers@qupracs.com",
            subjectPrefix: "Application",
            instructions: ["Include one scope/POV example (or outline) you tightened to protect outcomes."],
            askFor: ["Resume or LinkedIn link", "One scope/POV sample", "Timezone / location"],
          },
        },
        {
          order: 4,
          slug: "full-stack-engineer-platform",
          title: "Full Stack Engineer (Platform)",
          track: "Engineering",
          team: "Engineering",
          locations: ["Remote (US-friendly hours)", "San Francisco Bay Area"],
          employmentType: "Full time",
          locationType: "Remote",
          focusTags: ["Platform"],
          summary: "Build simple, reliable product workflows: site + tooling + learning/tutorial plumbing—optimized for shipping and low ops burden.",
          credibilityBullets: {
            outcome90Days: "Ship 2–4 end-to-end improvements across content + tutorials + internal workflows with clean reliability.",
            skills: "TypeScript/React/Next.js, pragmatic API work, and comfort owning features end-to-end.",
            niceToHave: "Experience with developer tooling, CI, content pipelines, or lightweight infra.",
          },
          overview: [
            "We value speed with correctness: simple systems that stay maintainable.",
            "You’ll help keep content, demos, and small tools cohesive and reliable.",
          ],
          responsibilities: [
            "Build and maintain web features and small internal tools.",
            "Improve reliability and clarity across the tutorial runner UX.",
            "Keep implementation simple: minimal moving parts, strong defaults.",
          ],
          requirements: [
            "Strong TypeScript/React fundamentals.",
            "Comfort shipping and maintaining production code.",
          ],
          application: {
            emailTo: "careers@qupracs.com",
            subjectPrefix: "Application",
            instructions: ["Share 1–2 links to systems you’ve shipped and maintained."],
            askFor: ["Resume or LinkedIn link", "Links to shipped work", "Timezone / location"],
          },
        },
        {
          order: 5,
          slug: "research-engineer-optimization-qc-applications",
          title: "Research Engineer (Optimization / QC Applications)",
          track: "Engineering",
          team: "Engineering",
          locations: ["Remote (US-friendly hours)", "San Francisco Bay Area"],
          employmentType: "Full time",
          locationType: "Remote",
          focusTags: ["Evaluation"],
          summary: "Build and benchmark problem formulations + baselines across solvers/QPUs/sim—keeping claims disciplined and decision-grade.",
          credibilityBullets: {
            outcome90Days: "Deliver 2–3 benchmarked evaluations with baselines, assumptions, and reproducible artifacts.",
            skills: "Optimization/applied math foundations, experimental discipline, and clean reproducible code.",
            niceToHave: "Familiarity with OR/MIP/QUBO/Ising or hybrid workflows; comfort writing clear decision memos.",
          },
          overview: [
            "We care about baseline-first evaluation and pragmatic constraints.",
            "You’ll turn vague use-cases into clear formulations and measurement plans.",
          ],
          responsibilities: [
            "Define formulations and compare against classical baselines.",
            "Build evaluation pipelines and produce decision-grade summaries.",
            "Partner with delivery to keep prototypes measurable and credible.",
          ],
          requirements: [
            "Strong analytical reasoning and comfort with experimentation.",
            "Ability to write clear, reproducible code.",
          ],
          application: {
            emailTo: "careers@qupracs.com",
            subjectPrefix: "Application",
            instructions: ["Share one example of a baseline you built and how you validated it."],
            askFor: ["Resume or LinkedIn link", "One baseline example", "Timezone / location"],
          },
        },
        {
          order: 10,
          slug: "intern-quantum-research-optimization-or",
          title: "Quantum Research Intern (Optimization / OR)",
          track: "Internships & Early Career",
          team: "Practice",
          locations: ["Remote (US-friendly hours)", "San Francisco Bay Area"],
          employmentType: "Internship",
          locationType: "Remote",
          focusTags: ["Evaluation"],
          compensation: "$30–$60/hr (scope-dependent)",
          summary: "Support benchmarking work: formulations, baselines, and short memos—shipping small, credible artifacts weekly.",
          credibilityBullets: {
            outcome90Days: "Ship 6–12 small research artifacts (benchmarks, notes, diagrams, short memos) with clean references.",
            skills: "Comfort with OR/optimization basics and structured writing.",
            niceToHave: "Python notebooks, light coding, and curiosity for experimental discipline.",
          },
          overview: [
            "You’ll learn by shipping: small benchmarks, baselines, and short readable summaries.",
            "This is practical work: reproducibility and clarity matter more than novelty.",
          ],
          responsibilities: [
            "Implement or reproduce baseline comparisons from papers/blogs.",
            "Write short memos: what worked, what didn’t, and what assumptions mattered.",
            "Maintain clean, searchable artifacts (notes + links + code snippets).",
          ],
          requirements: [
            "Clear communication and strong follow-through.",
            "Comfort being coached and iterating fast.",
          ],
          application: {
            emailTo: "careers@qupracs.com",
            subjectPrefix: "Internship application",
            instructions: ["Email us a short note and one sample (writing, analysis, or code)."],
            askFor: ["Resume or LinkedIn link", "One sample", "Timezone / location"],
          },
        },
        {
          order: 11,
          slug: "intern-software-engineering-platform-full-stack",
          title: "Software Engineering Intern (Platform / Full Stack)",
          track: "Internships & Early Career",
          team: "Engineering",
          locations: ["Remote (US-friendly hours)", "San Francisco Bay Area"],
          employmentType: "Internship",
          locationType: "Remote",
          focusTags: ["Platform"],
          compensation: "$30–$60/hr (scope-dependent)",
          summary: "Ship small end-to-end improvements across the site and tutorial experience with good hygiene and fast iteration.",
          credibilityBullets: {
            outcome90Days: "Ship 4–8 small PRs that improve reliability, UX, or content plumbing.",
            skills: "Basic web dev fundamentals (React/TypeScript) and a bias to shipping.",
            niceToHave: "Comfort with testing, CI, or working in a modern Next.js codebase.",
          },
          overview: [
            "You’ll work in a real codebase with real constraints.",
            "We prefer small, shippable improvements over sprawling rewrites.",
          ],
          responsibilities: [
            "Implement small features and fixes across site and tutorials.",
            "Improve developer ergonomics (docs, scripts, reliability).",
            "Write clear PR descriptions and accept feedback.",
          ],
          requirements: [
            "Comfort learning quickly and asking crisp questions.",
            "Care for code clarity and maintainability.",
          ],
          application: {
            emailTo: "careers@qupracs.com",
            subjectPrefix: "Internship application",
            instructions: ["Email us a short note and a link to one project/repo (or a short sample)."],
            askFor: ["Resume or LinkedIn link", "One project/repo link", "Timezone / location"],
          },
        },
        {
          order: 12,
          slug: "intern-content-research-briefs-blogs",
          title: "Content & Research Intern (Executive Briefs + Blogs)",
          track: "Internships & Early Career",
          team: "Product & Content",
          locations: ["Remote (US-friendly hours)", "San Francisco Bay Area"],
          employmentType: "Internship",
          locationType: "Remote",
          focusTags: ["Content"],
          compensation: "$25–$55/hr (scope-dependent)",
          summary: "Turn reading and delivery notes into crisp artifacts: briefs, diagrams, and blog drafts that stay decision-first.",
          credibilityBullets: {
            outcome90Days: "Ship 6–10 publishable drafts or internal briefs with clean structure and citations.",
            skills: "Strong writing, editing, and ability to distill messy inputs into a clear outline.",
            niceToHave: "Comfort with technical topics and simple visual diagrams.",
          },
          overview: [
            "We write for decision-makers and builders: baseline-first, measurable, hype-resistant.",
            "You’ll ship weekly: short artifacts with clear structure.",
          ],
          responsibilities: [
            "Draft executive briefs and blog outlines from source material.",
            "Edit for clarity, tone, and measurable claims.",
            "Maintain a simple backlog of topics and supporting links.",
          ],
          requirements: [
            "Excellent writing and comfort receiving feedback.",
            "Strong organizational habits.",
          ],
          application: {
            emailTo: "careers@qupracs.com",
            subjectPrefix: "Internship application",
            instructions: ["Email us a short note and one writing sample (published or private)."],
            askFor: ["Resume or LinkedIn link", "One writing sample", "Timezone / location"],
          },
        },
        {
          order: 13,
          slug: "intern-go-to-market-lead-research-outreach-ops",
          title: "Go-to-Market Intern (Lead Research + Outreach Ops)",
          track: "Internships & Early Career",
          team: "Sales Ops",
          locations: ["Remote (US-friendly hours)", "San Francisco Bay Area"],
          employmentType: "Internship",
          locationType: "Remote",
          compensation: "$25–$50/hr (scope-dependent)",
          summary: "Support lead research, outreach ops, and CRM hygiene—helping the team keep the funnel high-signal.",
          credibilityBullets: {
            outcome90Days: "Build 1–2 tight lead lists and keep outreach + CRM hygiene clean and measurable.",
            skills: "Strong organization, writing, and comfort with systems (spreadsheets/CRM).",
      instructions: ["Include one tutorial or repo you’re proud of."],
      askFor: ["Resume or LinkedIn link", "One content link", "Timezone / location"],
    },
  },
  {
    order: 14,
    slug: "technical-writer-quantum-decision-making",
    title: "Technical Writer (Quantum & Decision-Making)",
    track: "Product, Learning & Thought Leadership",
    team: "Product & Content",
    locations: ["Remote (US-friendly hours)"],
    employmentType: "Full time",
    locationType: "Remote",
    focusTags: ["Content", "Quantum Readiness"],
    compensation: "$110K–$170K (DOE)",
    summary: "Write constraint-pragmatic learning content: what’s real, what’s not, and how to decide—without oversimplifying truth.",
    overview: [
      "You’ll produce Learning pages, blogs, and tutorials with a consistent voice.",
      "You’ll make complex topics usable and precise.",
    ],
    responsibilities: [
      "Turn messy notes into crisp Learning content.",
      "Develop diagrams, checklists, and decision frameworks.",
      "Maintain editorial standards and reduce ambiguity.",
    ],
    requirements: [
      "Strong technical writing portfolio.",
      "Ability to explain assumptions, tradeoffs, and limits.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Send 2–3 writing samples and a short note about your process."],
      askFor: ["Resume or LinkedIn link", "2–3 writing samples", "Timezone / location"],
    },
  },
  {
    order: 15,
    slug: "curriculum-lead-qupracs-learning-track-quantum-readiness",
    title: "Curriculum Lead (QuPracs Learning Track — Quantum Readiness)",
    track: "Product, Learning & Thought Leadership",
    team: "Product & Content",
    locations: ["Remote (US-friendly hours)"],
    employmentType: "Full time",
    locationType: "Remote",
    focusTags: ["Content", "Quantum Readiness"],
    compensation: "$130K–$190K (DOE)",
    summary: "Own the Learning track end-to-end: structure, pedagogy, and high-signal content that reduces confusion and hype.",
    overview: [
      "You’ll define learning objectives and content standards.",
      "You’ll coordinate SMEs and ship coherent curriculum.",
    ],
    responsibilities: [
      "Define scope and sequencing of the readiness curriculum.",
      "Review and edit content for clarity, precision, and usefulness.",
      "Measure content effectiveness and iterate.",
    ],
    requirements: [
      "Strong curriculum design and writing/editing skills.",
      "Ability to balance accessibility with technical truth.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Include one curriculum artifact you’ve owned (outline, syllabus, or learning path)."],
      askFor: ["Resume or LinkedIn link", "One curriculum artifact", "Timezone / location"],
    },
  },
  {
    order: 16,
    slug: "account-executive-enterprise-qupracs-quantum-advisory",
    title: "Account Executive (Enterprise — QuPracs Quantum Advisory)",
    track: "Sales & Revenue",
    team: "Sales",
    locations: ["San Francisco Bay Area", "Remote (US-friendly hours)"],
    employmentType: "Full time",
    locationType: "Hybrid",
    focusTags: ["Quantum Readiness"],
    compensation: "$120K–$170K base + commission",
    summary: "Sell carefully: help execs buy clarity and readiness, not demos—measured on trust, retention, and decision outcomes.",
    overview: [
      "You’ll qualify enterprise accounts and run discovery with Practice.",
      "You’ll scope readiness engagements with clear deliverables.",
    ],
    responsibilities: [
      "Prospect and qualify enterprise accounts.",
      "Coordinate discovery and scope proposals.",
      "Maintain high-signal pipeline hygiene.",
    ],
    requirements: [
      "Enterprise sales experience in technical services or SaaS.",
      "Comfort selling nuance and constraints.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Include one example of slowing a deal down to protect trust—and why."],
      askFor: ["Resume or LinkedIn link", "One trust-first sales story", "Timezone / location"],
    },
  },
  {
    order: 17,
    slug: "revenue-operations-lead-enterprise",
    title: "Revenue Operations Lead (Enterprise)",
    track: "Sales & Revenue",
    team: "Sales Ops",
    locations: ["Remote (US-friendly hours)", "San Francisco Bay Area"],
    employmentType: "Full time",
    locationType: "Remote",
    focusTags: ["Platform"],
    compensation: "$120K–$180K (DOE)",
    summary: "Build a clean operating system for growth: pipeline metrics, process, and instrumentation—high signal, low busywork.",
    overview: [
      "You’ll define funnel metrics and create pragmatic reporting.",
      "You’ll reduce friction across handoffs.",
    ],
    responsibilities: [
      "Instrument funnel and forecast inputs.",
      "Own CRM hygiene standards and automation.",
      "Partner with Sales/Practice to improve handoffs.",
    ],
    requirements: [
      "RevOps experience with strong analytics.",
      "Comfort building simple, maintainable systems.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Share one metric system you built and how it changed decisions."],
      askFor: ["Resume or LinkedIn link", "Metrics system example", "Timezone / location"],
    },
  },
  {
    order: 18,
    slug: "sales-engineer-qupracs-quantum-readiness-pocs",
    title: "Sales Engineer (QuPracs Quantum Readiness & POCs)",
    track: "Sales & Revenue",
    team: "Sales",
    locations: ["San Francisco Bay Area", "Remote (US-friendly hours)"],
    employmentType: "Full time",
    locationType: "Hybrid",
    focusTags: ["Quantum Readiness", "Prototyping"],
    compensation: "$150K–$220K (DOE) + variable",
    summary: "Bridge sales and delivery: run technical discovery, scope POCs pragmaticly, and protect credibility with baseline-first framing.",
    overview: [
      "You’ll support discovery and solution framing for enterprise prospects.",
      "You’ll keep proposals measurable and constraint-pragmatic.",
    ],
    responsibilities: [
      "Run technical discovery and produce solution narratives.",
      "Define baselines, metrics, and POC scope.",
      "Coordinate with engineering to validate feasibility.",
    ],
    requirements: [
      "Strong technical communication and stakeholder skills.",
      "Ability to translate constraints into credible plans.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Include one example of a POC you scoped to protect outcomes."],
      askFor: ["Resume or LinkedIn link", "One POC story", "Timezone / location"],
    },
  },
  {
    order: 19,
    slug: "operations-manager",
    title: "Operations Manager",
    track: "Operations",
    team: "Operations",
    locations: ["San Francisco Bay Area"],
    employmentType: "Full time",
    locationType: "On-site",
    focusTags: ["Platform"],
    compensation: "$110K–$160K (DOE)",
    summary: "Own the operational backbone: scheduling, vendor management, basic finance ops, and process hygiene so delivery stays focused.",
    overview: [
      "You’ll reduce friction and keep execution smooth.",
      "You’ll build simple processes that scale.",
    ],
    responsibilities: [
      "Manage scheduling and operational logistics.",
      "Maintain vendors, purchasing workflows, and internal process docs.",
      "Support light finance ops (invoicing coordination, budget tracking).",
    ],
    requirements: [
      "Strong organization and written communication.",
      "Ability to prioritize and reduce chaos.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Application",
      instructions: ["Include an example of a process you simplified and how you measured improvement."],
      askFor: ["Resume or LinkedIn link", "Process improvement example", "Timezone / location"],
    },
  },
  {
    order: 20,
    slug: "recruiting-talent-partner-qupracs-practice-engineering",
    title: "Recruiting / Talent Partner (QuPracs Practice & Engineering)",
    track: "Operations",
    team: "Operations",
    locations: ["Remote (US-friendly hours)"],
    employmentType: "Contract",
    locationType: "Remote",
    focusTags: ["Platform"],
    compensation: "$60–$120/hr (scope-dependent)",
    summary: "Own talent pipeline for Practice and Engineering: sourcing, screening, and process quality—high signal, low noise.",
    overview: [
      "You’ll build a repeatable recruiting motion that matches our judgment-first bar.",
      "You’ll maintain a fair, transparent process and strong candidate experience.",
    ],
    responsibilities: [
      "Source and screen candidates for key roles.",
      "Run a structured pipeline with clean notes and rubrics.",
      "Partner with hiring leads to keep interviews calibrated.",
    ],
    requirements: [
      "Recruiting experience across technical and client-facing roles.",
      "Strong communication and process discipline.",
    ],
    application: {
      emailTo: "careers@qupracs.com",
      subjectPrefix: "Talent partnership",
      instructions: ["Email a short note and examples of roles you’ve filled end-to-end."],
      askFor: ["LinkedIn link", "Roles filled (examples)", "Availability", "Timezone / location"],
    },
  },
];

*/
